# Generated by Django 5.2.16 on 2026-07-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDevelopment',
            fields=[
                ('faculty_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('academic_rank', models.CharField(max_length=30)),
                ('teaching_experience_years', models.PositiveSmallIntegerField()),
                ('research_experience_years', models.PositiveSmallIntegerField()),
                ('department', models.CharField(db_index=True, max_length=50)),
                ('university_type', models.CharField(max_length=20)),
                ('institution_digital_infrastructure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('institutional_support_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('big_data_readiness_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lms_usage_frequency', models.CharField(max_length=20)),
                ('online_teaching_hours_per_week', models.DecimalField(decimal_places=1, max_digits=4)),
                ('digital_tool_usage_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_literacy_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ai_tool_adoption_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('track_technology_knowledge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('track_research_analytics_knowledge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('track_academic_content_knowledge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('track_collaborative_knowledge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('track_knowledge_integration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_feedback_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teaching_effectiveness_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('research_publications', models.PositiveSmallIntegerField()),
                ('research_productivity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('publication_quality_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('training_programs_attended', models.PositiveSmallIntegerField()),
                ('professional_development_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collaboration_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('innovation_in_teaching_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('administrative_participation_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_faculty_development_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('competency_level', models.CharField(db_index=True, max_length=20)),
                ('target', models.CharField(db_index=True, max_length=30)),
                ('loaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faculty_development',
                'indexes': [models.Index(fields=['department', 'academic_rank'], name='faculty_dev_departm_b10818_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacultyDevelopmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=40)),
                ('scope_key', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('faculty_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faculty_development_profiles',
                'unique_together': {('scope', 'scope_key')},
            },
        ),
    ]
