# Generated by Django 5.2.16 on 2026-08-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_facultydevelopment_facultydevelopmentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
