# Generated by Django 5.2.16 on 2026-08-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('url', models.TextField()),
                ('allowlist_id', models.CharField(blank=True, max_length=100)),
                ('outcome', models.CharField(choices=[('ok', 'Fetched'), ('cached', 'Served from cache'), ('refused', 'Refused (not allowlisted / unsafe target)'), ('failed', 'Fetch failed')], db_index=True, max_length=10)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('bytes_returned', models.IntegerField(default=0)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('injection_lines_removed', models.IntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
                ('question', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'web_fetch_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
