# Copyright (c) 2026 Yash Garad. All rights reserved.

# Generated by Django 5.2.16 on 2026-07-24 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('question', models.TextField()),
                ('route', models.CharField(max_length=10)),
                ('original_answer', models.TextField()),
                ('final_answer', models.TextField()),
                ('claim_text', models.TextField()),
                ('supported', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('evidence', models.TextField(blank=True)),
                ('action_taken', models.CharField(choices=[('passed', 'Passed'), ('corrected', 'Corrected using source data'), ('flagged_unverifiable', 'Flagged as unverifiable')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verification_logs',
            },
        ),
    ]
