# Copyright (c) 2026 Yash Garad. All rights reserved.

# Generated by Django 5.2.16 on 2026-07-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('question', models.TextField()),
                ('route', models.CharField(blank=True, max_length=10)),
                ('agents_used', models.CharField(blank=True, max_length=20)),
                ('generated_sql', models.TextField(blank=True, null=True)),
                ('final_answer', models.TextField(blank=True)),
                ('injection_flags', models.TextField(blank=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
