# Generated by Django 5.2.16 on 2026-08-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('question', models.TextField()),
                ('route', models.CharField(blank=True, max_length=10)),
                ('total_ms', models.FloatField()),
                ('ttft_ms', models.FloatField(blank=True, null=True)),
                ('router_ms', models.FloatField(blank=True, null=True)),
                ('sql_ms', models.FloatField(blank=True, null=True)),
                ('rag_ms', models.FloatField(blank=True, null=True)),
                ('web_ms', models.FloatField(blank=True, null=True)),
                ('synthesis_ms', models.FloatField(blank=True, null=True)),
                ('verification_ms', models.FloatField(blank=True, null=True)),
                ('overhead_ms', models.FloatField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('prompt_ms', models.FloatField(blank=True, null=True)),
                ('gen_tokens', models.IntegerField(blank=True, null=True)),
                ('gen_ms', models.FloatField(blank=True, null=True)),
                ('verification_tier', models.CharField(blank=True, max_length=10)),
                ('cached', models.CharField(blank=True, max_length=16)),
                ('stages', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'query_profile',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='query_profi_created_2762ab_idx')],
            },
        ),
    ]
